#!/bin/bash

usage()
{
  cat <<EOF

$1 command

  Available commands:

  create      Creates one of the following containers
    core      Base Ubuntu container
    buildbox  Base Build container
    buildroot Buildroot container (requires core and buildbox)

    build     
      000     creates build000

    node
      000     creates node000

  build       Builds one of the following packages
    aethos    (requires buildroot)

EOF
}

# x86_64
#arch=`uname -m`

# amd64
arch=`dpkg --print-architecture`

roots="/var/lib/lxc/_roots"

createCore()
{
  if [ ! -d "/var/lib/lxc" ]; then
    echo "/var/lib/lxc must exist.  Has lxc been installed?"
    exit 1
  fi

  if [ -d "/var/lib/lxc/ubuntu" ]; then
    echo "Ubuntu base distro is already installed."
  else
    echo "About to do this; needs sudo"
    echo "sudo lxc-create -t download -n ubuntu -- --dist ubuntu --release bionic --arch $arch --keyserver hkp://p80.pool.sks-keyservers.net:80"
    read -n 1 -s
    sudo lxc-create -t download -n ubuntu -- --dist ubuntu --release bionic --arch $arch --keyserver hkp://p80.pool.sks-keyservers.net:80
  fi

  if [ ! -d $roots ]; then
    sudo mkdir $roots
    sudo mkdir $roots/core
  fi

  if [ ! -f "$roots/core.squash" ]; then
    sudo mksquashfs "/var/lib/lxc/ubuntu/rootfs" "$roots/core.squash"
  else
    echo "core file system has already been created."
  fi

  if [ ! -d $roots/core/etc ]; then
    sudo mount $roots/core.squash -t squashfs $roots/core
  fi

}

createBuildBox()
{
  createCore

  if [ -d "/var/lib/lxc/buildbox" ]; then
    echo "BuildBox base container is already installed."
  else
    sudo lxc-create -t aethos -n buildbox -- -t buildbox
  fi

  if [ -f "$roots/buildbox.squash" ]; then
    echo "Buildbox file system has already been created"
  else
    sudo lxc-start -n buildbox
    sleep 10
    sudo lxc-attach -n buildbox -- /root/abd/update_buildbox.sh
    sleep 10
    sudo lxc-stop -n buildbox
    sleep 10
    sudo mksquashfs "/var/lib/lxc/buildbox/upper" "$roots/buildbox.squash"

    sudo mkdir $roots/buildbox
    sudo mkdir $roots/buildbox.upper
    sudo mount $roots/buildbox.squash $roots/buildbox.upper

    sudo unionfs-fuse $roots/buildbox.upper:$roots/core $roots/buildbox

  fi

}

createBuildRoot()
{
  createBuildBox

  if [ -d "/var/lib/lxc/buildroot" ]; then
    echo "buildroot container is already installed."
  else
    sudo lxc-create -t aethos -n buildroot -- -t buildroot
  fi

}

# Verify the command was set.
if [ -z $1 ]; then
  echo Command must be specified.
  usage $(basename $0)
  exit 1
fi

options=$(getopt -o hxrtfm -l help x86_64 rpi tk1 full min -- "$@")
if [ $? -ne 0 ]; then
    usage $(basename $0)
    exit 1
fi

cmd=$1
shift 1

createUsage()
{
  echo "Don't know how to create \"$1\"."
  echo "Usage: "
  echo "    apm create core"
  echo "    apm create buildbox"
  echo "    apm create buildroot"
}

doCreate()
{
  case $1 in
    core)       createCore;;
    buildbox)   createBuildBox;;
    buildroot)  createBuildRoot;;
    *)          createUsage; exit 1;;
  esac
}

case ${cmd} in
  create)       doCreate $@; exit 0;;
  *)            echo Bad command && usage $0 && exit 0;;
esac
